<?php

namespace Tests\Support\CheckGolden;

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\File;
use PHPUnit\Framework\Assert;

/**
 * Captures `bridge:check`'s operator-facing output + exit code and compares it against
 * a stored golden file (DL-242 stage 0).
 *
 * This is the safety net stages 1-7 refactor under: each stage moves one check unit out
 * of `handle()` into a `Check`, registered at the same ordinal position, and this
 * comparison is what makes "no operator-visible change" a measured claim instead of an
 * intention.
 *
 * THE BOUND, STATED RATHER THAN OVERSOLD: it holds only over the install shapes the
 * fixtures cover, and only over behavior that reaches stdout. A predicate whose two
 * branches print the same bytes is invisible here no matter how many fixtures exist —
 * which is why the gap disclosure is generated by MUTATION (does flipping this predicate
 * change any golden file?) rather than by asserting coverage. See
 * `docs/check-golden-coverage.md` — which carries a bound of its own, narrower than this
 * one: it is generated from `CheckCommand::handle()` alone, so a check that has migrated
 * into the registry is absent from it by construction, and absence there is not protection.
 *
 * NORMALIZATION IS DELIBERATELY MINIMAL. The plan forbids normalizing anything that
 * encodes a verdict, so only two classes of substitution happen, and neither can erase
 * one: absolute paths (the verdict is "absent" / "not writable" / "insecure", which
 * survives the path becoming a token) and the numeric uid (the verdict is "not writable
 * by this user"). Everything else — including the two divergent `$COORD_CONFIG`
 * diagnoses — is PINNED by {@see PinnedHost}, not normalized.
 */
final class GoldenCapture
{
    public const DIR = 'tests/Fixtures/check-golden';

    /**
     * Run the command and return its normalized capture: exit code, then output.
     *
     * @param  array<string, mixed>  $args
     */
    public static function capture(string $installRoot, array $args = []): string
    {
        $exit = Artisan::call('bridge:check', $args);

        return "exit: {$exit}\n--- output ---\n".self::normalize(Artisan::output(), $installRoot);
    }

    private static function normalize(string $output, string $installRoot): string
    {
        $uid = function_exists('posix_getuid') ? (string) posix_getuid() : '?';

        return str_replace(
            [rtrim($installRoot, '/'), rtrim(base_path(), '/'), "(uid {$uid})"],
            ['<INSTALL>', '<APP>', '(uid <UID>)'],
            $output,
        );
    }

    /**
     * Compare a capture against `tests/Fixtures/check-golden/<name>.txt`.
     *
     * Set `UPDATE_GOLDEN=1` to (re)write the file instead of asserting. That is a
     * deliberate escape hatch for the stages that legitimately change output (8-10) and
     * for adding a fixture — never a way to green a stage 1-7 diff. A regenerated golden
     * file must be READ in the PR diff: it is the operator-visible change, and reviewing
     * it is the point of the harness.
     */
    public static function assertMatchesGolden(string $name, string $capture): void
    {
        $path = base_path(self::DIR."/{$name}.txt");

        if (getenv('UPDATE_GOLDEN') === '1') {
            File::ensureDirectoryExists(dirname($path));
            File::put($path, $capture);
            Assert::assertTrue(true, 'golden file regenerated');

            return;
        }

        Assert::assertFileExists($path, "missing golden file for fixture '{$name}' — run with UPDATE_GOLDEN=1 to create it, then READ the diff");
        Assert::assertSame(
            File::get($path),
            $capture,
            "bridge:check output changed for fixture '{$name}'. Stages 0-7 hold a byte-identical contract: either the refactor changed behavior (fix the code), or the change is intended (regenerate with UPDATE_GOLDEN=1 and justify the diff in the PR).",
        );
    }
}
